name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main

pool: 'hetzner04'

#variables:
#  - group: traingen-secrets

steps:
  - task: Bash@3
    displayName: Prepare
    inputs:
      targetType: 'inline'
      script: |
        kubectl cluster-info
        cd $(Build.SourcesDirectory)/frontend
        npm i
        npm run openapi
        npm run build

  - task: Docker@2
    displayName: Build the frontend image
    inputs:
      workingDirectory: $(Build.SourcesDirectory)/frontend
      repository: eblovich/traingen-http
      command: buildAndPush
      addPipelineData: false
      dockerfile: '$(Build.SourcesDirectory)/frontend/Dockerfile'
      tags: $(Build.BuildNumber)

  - task: Bash@3
    displayName: Prepare dockerfile for backend
    inputs:
      targetType: 'inline'
      script: |
        docker run -u 1000:1002 -i --log-driver=none -a stdin -a stdout -a stderr -e COURSIER_CACHE=/cache/coursier  -v /usr/bin/docker:/sbin/docker -v /var/run/docker.sock:/var/run/docker.sock -v $(Build.SourcesDirectory):/root -v /data/cache/agent:/cache --rm sbtscala/scala-sbt:graalvm-community-22.0.1_1.10.7_3.6.2 sbt -Dsbt.global.base=/cache/.sbt -Dsbt.boot.directory=/cache/.sbt -Divy.home=/cache/.ivy2 -Dsbt.ivy.home=/cache/.ivy2 compile Docker/stage service/GraalVMNativeImage/packageBin

  - task: Docker@2
    displayName: Build the backend image
    inputs:
      workingDirectory: $(Build.SourcesDirectory)
      repository: eblovich/traingen-service
      command: buildAndPush
      addPipelineData: false
      dockerfile: '$(Build.SourcesDirectory)/service/target/docker/stage/Dockerfile'
      tags: $(Build.BuildNumber)

  - task: Bash@3
    displayName: Deploy site
    inputs:
      targetType: 'inline'
      script: |
        export APP_VERSION=$(Build.BuildNumber)
        # export DATABASE_PASSWORD=$(DATABASE_PASSWORD) 
        cat deployment.yaml | envsubst | kubectl apply -f -
