openapi: 3.0.1
info:
  title: Training Generator API
  description: API for trainings
  version: 1.0.0

servers:
  - url: http://localhost:8080/

paths:

  /user/api/combo/make:
    get:
      summary: Make combo
      operationId: getCombo
      responses:
        200:
          $ref: '#/components/responses/ComboInstance'

  /user/api/combo/movements:
    get:
      summary: Make combo
      operationId: getMovements
      responses:
        200:
          $ref: '#/components/responses/ComboMovements'

components:
  responses:
    ComboInstance:
      description: Combo instance
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ComboInstance'

    ComboMovements:
      description: Combo movements
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ComboMovement'
  schemas:
    ComboInstance:
      description: A combo of movements
      type: object
      required:
        - duration
        - movements
      properties:
        duration:
          type: string
          x-scala-type: scala.concurrent.duration.FiniteDuration
        movements:
          description: Sequence of movements
          type: array
          items:
            $ref: '#/components/schemas/ComboMovementInstance'

    ComboMovementInstance:
      description: A movement used in combo
      type: object
      required:
        - id
        - description
      properties:
        id:
          type: string
        description:
          type: string
        picture:
          type: string
        video:
          type: string


    ComboMovement:
      description: A movement that makes combos
      type: object
      required:
        - id
        - description
        - type
        - bodyPart
        - after
      properties:
        id:
          type: string
        description:
          type: string
        bodyPart:
          type: string
          x-scala-type: nl.pragmasoft.traingen.BodyPart
        picture:
          type: string
        video:
          type: string
        after:
          type: array
          items:
            $ref: '#/components/schemas/ComboMovementChance'
        excludes:
          type: array
          items:
            type: string

    ComboMovementChance:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        chance:
          type: number
          x-scala-type: Double
